name: Keycloak Docker CI/CD

on:
  workflow_dispatch:
   inputs:
      version:
        description: 'Version number'
        required: true
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_DEV_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
          context: ./src
          file: ./src/Doosy.API/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_HUB_REPO }}:${{ env.IMAGE_TAG }}
            ${{ env.DOCKER_HUB_REPO }}:${{ github.event.inputs.version }}

    - name: Deploy Keycloak container on server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_DEV_USERNAME }}/keycloak:latest
          docker stop keycloak || true
          docker rm keycloak || true
          docker run -d --name keycloak -p 8080:8080 \
            -e KEYCLOAK_ADMIN=${{ secrets.KEYCLOAK_ADMIN_USER }} \
            -e KEYCLOAK_ADMIN_PASSWORD=${{ secrets.KEYCLOAK_ADMIN_PASSWORD }} \
            ${{ secrets.DOCKER_DEV_USERNAME }}/keycloak:latest
    - name: Wait for Keycloak to be ready
      run: |
        for i in {1..30}; do
          if curl -s http://your-server-ip:8080/auth/realms/master; then
            echo "Keycloak is up"
            break
          fi
          echo "Waiting for Keycloak..."
          sleep 10
        done

    - name: Configure Keycloak realms and clients
      uses: carlosthe19916/keycloak-action@0.7
      with:
        server: http://your-server-ip:8080/auth
        username: ${{ secrets.KEYCLOAK_ADMIN_USER }}
        password: ${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}
        kcadm: |
          create realms -f ./keycloak/realm.json
          create clients -r DoosyFramework -f ./keycloak/client.json
